export const IS_LOADING = "IS_LOADING";
export const GET_TABLE_SUCCESS = "GET_TABLE_SUCCESS";
export const GET_TABLE_ERROR = "GET_TABLE_ERROR";
export const GET_TRIALS_SUCCESS = "GET_TRIALS_SUCCESS";
export const GET_TRIALS_ERROR = "GET_TRIALS_ERROR";
